# Which files to compile as part of the project
OBJS = TripleX.cpp 

# Which compiler we're using
CC = g++

# Additionnal compilation options we're using
COMPILER_FLAGS = -w

# Libraries we're linking against
LINKER_FLAGS = -lglfw -lGLEW

# Name of our executable
OBJ_NAME = tripleX

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) -o $(OBJ_NAME)